/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jak;

import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class ApplicationTest {
	
	public void contextLoads() {
	}
}
