/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jak.product.api;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;


@SpringBootTest
public class ApplicationTest {
	
	public ApplicationTest() {
		
	}
	
    @Test 
    public void testSomeLibraryMethod() {
        
    }
}
